### ISSUE TITLE
iteration 1

### ISSUE THREAD

**Issue by relimo** [relimo/seproject-team-template#28]
## iteration 1 is ready!!!!

meanwhile the project is not deployed in AZURE  and Reuven said it's OK.
Tests to iteration 1:
1. **test:** press in nav bar on "login" <br>
   **expected result:** the page "login" will be shown
2. **test:**fill in existing user name and password  (there is a need to see the table "client" if it really exists)<br>
   **expected result:**  the page "individual" will be shown with the lessons which this specific is registered to.
3. **test:**press the delete button in one of the lines <br>
   **expected result:**  this line will not be shown anymore and also in the table "lessons_of_clients" this line was deleted.

**Comment by robi-y** [comment]
👍
