### ISSUE TITLE
sds 

### ISSUE THREAD

**Issue by relimo** [relimo/seproject-team-template#3]
link to our sds :    https://github.com/relimo/JumpAPP/wiki/sds

**Comment by evelev** [comment]
איזו עבודה יפה עשיתם, כל הכבוד!
אני רק יכולה לתאר לעצמי כמה שעות זה לקח... המון תודה!

2016-03-29 23:49 GMT+03:00 relimo notifications@github.com:

**Comment by hadarp** [comment]
Checked.
SDS Review Summary - missing.
Incomplete User Guide.
