### ISSUE TITLE
iteration 2

### ISSUE THREAD

**Issue by elishla** [relimo/seproject-team-template#31]
iteration 2 is ready!!!!

(meanwhile the project is not deployed in AZURE and Reuven said it's OK.)

the wiki page for iteration 2 is:
https://github.com/relimo/JumpAPP/wiki/Iteration-2

**Comment by robi-y** [comment]
As we discussed on class the page behind architecture is not considered to be a good engineering.
Also need to close issues so the board reflects current iteration only
Iteration page - missing link to next iteration page (planning should be held over there)

**Comment by elishla** [comment]
we did not know that Also need to close issues so the board reflects current iteration only, so we did it after you told us.
and we added a the missing link to next iteration page after you told us,
it was all planed in the uboard .

**Comment by elishla** [comment]
@robi-y

**Comment by robi-y** [comment]
Hi,
I added some points to tasks and next iteration plan (grade now for iteration 94)
Regards
